version: '3.7'

services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    container_name: mysql
    environment:

  php:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: PHPMyAdmin
    ports:
      - "8080:80"
    restart: always
    PMA_HOST: db
    environment:
      MYSQL_ROOT_PASSWORD: 'Qawsed123'