Vagrant.configure("2") do |config|                      # Version der Konfiguration
  config.vm.box = "ubuntu/xenial64"                     # Base-Box
  v.name = "VM01"                                       # Name der VM in virtualbox
  config.vm.provider "virtualbox" do |vb|               # Virtualisierungsplatform
    vb.memory = "1024"                                  # Grösse RAM
  config.vm.network "public_network", ip: "10.71.13.18" # Netzwerkkonfig. Nicht sicher ob "public_network" oder "privat_Network". IP wie in Tabelle
end
config.vm.provision "shell", inline: <<-SHELL           #Anfang der Befehle
  sudo mkdir /test

SHELL  
end
