version: '3.7'                          # Version von docker-compose.yml
services:                               # Auflistung der Services
  db:                                   # Anfang MySQL Service
    image: mysql:5.7                    # Docker Image
    container_name: mysql               # Containername
    networks:                           # Anfang Netzwerkkonfiguration
    - Net1                              # Net1 als Netzwerk gesetzt
    restart: always                     # Nach erstellen Neustarten
    environment:                        # Anfang environment Parameter
      MYSQL_ROOT_PASSWORD: 'Qawsed123'  # Rootpasswort von MySQL setzen
      MYSQL_DATABASE: New_Database      # Neue Datenbank erstellt

  php:                                  # Anfang PHPMyAdmin Service
    depends_on:                         # Anfang Abhänigkeit
      - db                              # Abhängig vom Service db
    image: phpmyadmin:latest            # Docker Image
    container_name: PHPMyAdmin          # Containername
    networks:                           # Anfang Netzwerkkonfiguration
    - Net1                              # Net1 als Netzwerk gesetzt
    ports:                              # Anfang Portmapping
      - "8080:80"                       # Container Port 80 auf Localhost Port 8080
    restart: always                     # Nach erstellen Neustarten
    environment:                        # Anfang environment Parameter
      PMA_HOST: db                      # MySQL Datenbank ist db

networks:                               # Anfang allgemeine Netzwerkkonfiguration
  Net1:                                 # Netzwerk Net1 erstellt