#
# LAM Umgebung

version: '2'
services:
 mysql:
  image: mysql
  ports:
   - 3306:3306
# Fehler: Volume Mount fuehrt zum Absturz des MySQL Daemons
# volumes:
#  - /vagrant/compose/data:/var/lib/mysql

 phpmyadmin:
  image: phpmyadmin
  ports:
   - 8080:80
  links:
  - mysql