version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    networks:
    - Net1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Qawsed123'
      MYSQL_DATABASE: New_Database

  php:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: PHPMyAdmin
    networks:
    - Net1
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db

networks:
  Net1: